version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Reactアプリケーションのデフォルトポート
    volumes:
      - ./my-app:/app/my-app  # ローカルホストの./my-appをコンテナ内の/app/my-appにマウント
